# Generated by Django 2.2.5 on 2019-11-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("staff", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="lectureschedule",
            name="schedule_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staff.Schedule"
            ),
        )
    ]
