# Generated by Django 2.2.5 on 2019-11-02 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("administrator", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="scheduletemplate", name="deleted"),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="academic_year",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrator.AcademicYear",
            ),
        ),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrator.Group",
            ),
        ),
    ]
